name: Deploy Python project to Azure Function App to check

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        shell: bash
        run: |
          pushd "${{ vars.AZURE_FUNCTIONAPP_PACKAGE_PATH }}"
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt --target=".python_packages/lib/site-packages"
          popd

      - name: Create deployment package
        shell: bash
        run: |
          cd "${{ vars.AZURE_FUNCTIONAPP_PACKAGE_PATH }}"
          zip -r ../functionapp-package.zip .
      
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: functionapp-package
          path: functionapp-package.zip


  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: dev
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: functionapp-package
          path: ${{ vars.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: false

      - name: Deploy with Azure CLI
        shell: bash
        run: |
          echo "Deploying Function App using Azure CLI..."
          az functionapp deployment source config-zip \
            --resource-group ${{ vars.AZURE_RESOURCE_GROUP }} \
            --name ${{ vars.AZURE_FUNCTIONAPP_NAME }} \
            --src "functionapp-package.zip"
